### ISSUE TITLE
Bubble a real error message on error screen

### ISSUE THREAD

**Issue by thiagopnts** [globocom/clappr#186]
We are currently using a generic error screen for unsupported playback types:

![](https://i.cloudup.com/URFGUz-U3r-3000x3000.png)

**Comment by flavioribeiro** [comment]
![image](https://cloud.githubusercontent.com/assets/244265/5787711/77ac3166-9df2-11e4-9101-524cfd3116fe.png)
from http://www.opentelly.com/benchmark/index.html on firefox

**Comment by flavioribeiro** [comment]
Tv Noisy examples:
http://codepen.io/Prashantsani/pen/FhgzA (css only)
https://github.com/criography/StaticGen
http://jsfiddle.net/78e0xys6/
http://jsfiddle.net/EnQKm/

**Comment by flavioribeiro** [comment]
http://stackoverflow.com/questions/22003491/animating-canvas-to-look-like-tv-noise

**Comment by flavioribeiro** [comment]
http://imgarcade.com/1/white-noise-animated-gif/

**Comment by flavioribeiro** [comment]
http://mashable.com/2012/08/02/youtube-easter-egg-error-message/#_

**Comment by flavioribeiro** [comment]
hey @thiagopnts @barbosa @towerz @karinasirqueira and whoever wants to opine. I made an error screen here and wanna know if should I push to master. Check it out [here](http://flv.io/error/). +1 or -1?

**Comment by barbosa** [comment]
Late, but +1 

:)
