### ISSUE TITLE
Wrong ui behavior if you try to stop the player twice

### ISSUE THREAD

**Issue by lucasmundim** [globocom/clappr#318]
With chromeless=true, the poster's play/[pause|stop] button appears and do not disappears anymore.

With chromeless=false, it has the same behavior of chromeless=true for the poster's play/[pause|stop] button but the mediacontrol bar disappears too.

**Comment by flavioribeiro** [comment]
hi @lucasmundim, it should be fixed now. Can you test with our master branch before I bump another version?
