### ISSUE TITLE
Option for disabling media controls?

### ISSUE THREAD

**Issue by ronag** [globocom/clappr#321]

**Comment by flavioribeiro** [comment]
@ronag try `chromeless: true` option

**Comment by ronag** [comment]
Great! How do I stop click = play?

**Comment by flavioribeiro** [comment]
@ronag you can control the player by using its javascript api. Try on your browser console: `p.stop()`
(assuming that we are dirtying the namespace [here](https://github.com/globocom/clappr/blob/master/src/components/player.js#L15) and the right way to do it is calling at your player instance)

**Comment by ronag** [comment]
calling p.stop() won't help me with disabling play on click.

**Comment by flavioribeiro** [comment]
oh, I got it wrong. This is something someone reported at #290, there's no way on disabling this for now. PR are welcome

**Comment by flavioribeiro** [comment]
tell us if you want help @ronag :beers:

**Comment by ronag** [comment]
Yea, I'll get to that. Need make the project work with webpack first.
