### ISSUE TITLE
resize is not defined

### ISSUE THREAD

**Issue by ronag** [globocom/clappr#325]
```javascript
Uncaught TypeError: undefined is not a function
$traceurRuntime.createClass.resizeclappr.min.js:3
$traceurRuntime.createClass.setPlayerSizeclappr.min.js:3 
$traceurRuntime.createClass.updateSizeclappr.min.js:3 
$traceurRuntime.createClass.renderclappr.min.js:3 
$traceurRuntime.createClass.setupContainersclappr.min.js:3 
(anonymous function)
clappr.min.js:6 
(anonymous function)
clappr.min.js:6 lclappr.min.js:6 h.addclappr.min.js:6
(anonymous function)
clappr.min.js:6 C.eachclappr.min.js:6 
(anonymous function)
clappr.min.js:6 eclappr.min.js:6
o.then
clappr.min.js:3
$traceurRuntime.createClass.createContainersclappr.min.js:3 
d
clappr.min.js:3 
$traceurRuntime.createClass.createclappr.min.js:3 
$traceurRuntime.createClass.attachTo
```

**Comment by ronag** [comment]
We need to check the options sent resize for "width and "height".

**Comment by ronag** [comment]
Well, I learned today to not use the latest CDN in production.

**Comment by ronag** [comment]
Same problem here: http://cdn.clappr.io

**Comment by flavioribeiro** [comment]
@ronag I've introduced this bug on 0.0.83 release, specially on resize() function at core component. It should be fixed now. Not absenting myself of guilt but we're not on `1.0.0` version yet and moving quickly, unexpected behaviors are kind of acceptable for now. If you're using it in production, I recommend you to pin on a version by changing `latest` for the one you want.

**Comment by ronag** [comment]
@ronag Nice. Note, not blaming anyone but myself.
