### ISSUE TITLE
HLS: flushLiveURLCache is not working on IE10

### ISSUE THREAD

**Issue by flavioribeiro** [globocom/clappr#327]

**Comment by shacharz** [comment]
How come this commit closed the issue? I still see it

**Comment by flavioribeiro** [comment]
afaik the `:flashready` event was not being triggered on IE10 or being triggered in wrong time causing `setFlashSettings()` to not be called so I forced the call again on `firstPlay`. Unfortunately I don't have an IE10 here to make tests. Mind printing `this.flushLiveURLCache` inside `setFlashSettings()` so we can ensure it's being called and that the param is set to `false`?
